name: Run prettier

on:
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout código
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Rodar prettier
        run: npx prettier --check .